## catalog of libraries and plugins used to build the Georg project

[versions]

checkstyle = "12.1.0"

[libraries]

heart = "com.github.stephengold:Heart:9.2.0"
imgscalr = "org.imgscalr:imgscalr-lib:4.2"

[bundles]

[plugins]
