---
# GitHub Actions workflow for commits pushed to the Georg repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew textures --console=plain --no-daemon --stacktrace

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - run: ./gradlew textures --console=plain --no-daemon --stacktrace
        shell: bash
