---
# GitHub Actions workflow for commits pushed to the Georg repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew textures --console=plain --stacktrace

  Java23-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: actions/checkout@v4
      - run: ./gradlew textures --console=plain --stacktrace
        shell: bash
